library(shiny)
library(shinythemes)
library(MASS)
library(ggplot2)
library(plotly)
source("G:/My Drive/HPCF project F17/HPCF project F17-v1.1/gendata.R")
source("G:/My Drive/HPCF project F17/HPCF project F17-v1.1/plotpdf.R")
source("G:/My Drive/HPCF project F17/HPCF project F17-v1.1/conplot.R")
ui <- source("ui.R")
server <- source("server.R")
shinyApp(ui = ui, server = server)
